# Generated by Django 3.1.7 on 2022-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='teste@teste.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='iniciomonitoramentoemdias',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tempomonitoramento',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='terminomonitoramentoemdias',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ticket',
            field=models.CharField(default='B3SA3.SA', max_length=450),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='teste', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='valormaior',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='valormenor',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=9),
        ),
    ]
