# Generated by Django 3.1.7 on 2022-04-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220403_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
